### ISSUE TITLE
performance on custom data

### ISSUE THREAD

**Issue by crazyMessi** [LeoQLi/NGLO#2]
Thank you for your excellent work! I am interested in understanding how your job works with custom data. I have successfully converted some ply files to the format as you have defined:

```
- \testset_{name}.txt #contain name of the models 
- model0.tidx #0:n-1
- model0.xyz #n*3
- model0.normals #n*3
...
```

However, I am unsure about the specific meaning of .tidx. For now, I have simply assigned values from 0 to n-1(n is the count of points in .xyz or .normals). The performance of NGL was not as good as in SceneNN. Could you please explain the true meaning of .tidx or suggest any modifications to the parameters that I should consider?
![image](https://github.com/LeoQLi/NGLO/assets/56535498/a1753879-3bf1-4a61-99fd-34ebcb65eb86)

**Comment by LeoQLi** [comment]
Thank you for your interest in our work. The ".pidx" files are first used by PCPNet and consist of some random point indexes of points. They are mainly used to evaluate normals of selected points, and have no impact on the training and testing of the algorithm.

**Comment by crazyMessi** [comment]
Thank you for your feedback. After adjusting the learning rate, the results have improved.
